#!/usr/bin/env sh

# exit on any error, unset variable, or failed piped commands
set -euo pipefail

# staged files with specific extension
FILES="$(git diff --cached --name-only --diff-filter=ACMR "*.sh" | sed 's| |\\ |g')"

if ! [ -x "$(command -v shfmt)" ]; then
    echo 'Warning: shfmt is not installed'
else
    if [ -n "${FILES}" ]; then
        echo "Running shfmt..."
        echo "${FILES}" | xargs shfmt -i 4 -ci -l -w -s
        echo "${FILES}" | xargs git add
    fi
fi

if ! [ -x "$(command -v shellcheck)" ]; then
    echo 'Warning: shellcheck is not installed'
else
    if [ -n "${FILES}" ]; then
        echo "Running shellcheck..."
        echo "${FILES}" | xargs shellcheck -x -P SCRIPTDIR
    fi
fi
