# https://github.com/tmux/tmux/wiki/Getting-Started#the-configuration-file

# Upgrade $TERM
set -g default-terminal "tmux-256color"

# iTerm2 Shell Integration https://gitlab.com/gnachman/iterm2/-/wikis/tmux-Integration-Best-Practices
set-option -g allow-passthrough on

# Set window titles
# e.g. echo -ne "\033kYour title goes here\007"
set-option -g set-titles on
set-option -g set-titles-string '#T'

# Scrollback limit
set -g history-limit 10000

# Enable mouse support
set -g mouse on

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# Focus events enabled for terminals that support them
set -g focus-events on

# Sync clipboard
set -g set-clipboard on
