keybindingsPerPlatform: true
ignoredSettings:
  - remote.SSH.remotePlatform
  - remote.defaultExtensionsIfInstalledLocally
  - settingsSync.ignoredExtensions
  - settingsSync.excludedExtensions
  - syncing.excludedSettings
  - syncing.excludedExtensions
resources:
  - keybindings
  - settings
